### ISSUE TITLE
met-office-cp license

### ISSUE THREAD

**Issue by enyst** [okfn/licenses#32]
This is a license I'm not sure it belongs in the repository.
- [Met-Office UK CP](http://www.metoffice.gov.uk/climatechange/science/monitoring/ukcp09/UKCIP08_license_agreement_130709.pdf) - doesn't seem an open license, at first sight it's non-commercial for some distributions, and requires an additional signed agreement from downstreams (probably more issues). It isn't tagged as approved, either.

There are non-conformant licenses in the repo, but they have or can have relevant explanations on the site (i.e. CC with -NC, widely used, is a case for which the explanation of non-conformance is useful for interested readers).

I think this license doesn't qualify as "common problematic licenses". I'm missing context for any government-related licenses though, I don't know if active non-conformant licenses are also supposed to be listed and discussed on the site.

Is there some reason or intention for keeping met-office-cp in the repo, or can we remove it?

**Comment by Stephen-Gates** [comment]
I think this licence is [in the csv](https://github.com/okfn/licenses/blob/master/licenses.csv#L99).

Can this be closed?

**Comment by rufuspollock** [comment]
WONTFIX.

@Stephen-Gates i think this was an issue about whether we should remove it. I agree we can close for now and reopen if we think it is an issue. (There is something of a desire to not clutter up the licenses.csv with "trivial" licenses - but we could address that probably with an "active" column or some such if needed).
