### ISSUE TITLE
Don't break identifiers

### ISSUE THREAD

**Issue by Floppy** [okfn/licenses#37]
We rely on the license IDs that you define here for other apps. When they change (like for capitalisation, or renaming), it breaks things downstream that depend on them.

I accept renaming needs to happen, but when it does, perhaps older deprecated IDs could be kept around with some sort of link to the new ID in its JSON representation?

**Comment by mlinksva** [comment]
https://github.com/okfn/licenses/pull/69/files#diff-df8c50fbd9842b77c087e6defc698cfa has a proposed rename and adds a `legacy_id` field with the old name. How about that?

**Comment by rufuspollock** [comment]
@mlinksva i think that could work. @Stephen-Gates any thoughts at your end.

**Comment by Stephen-Gates** [comment]
@rufuspollock I've highlighted this thread to ODI Labs who I believe use the data.

**Comment by mlinksva** [comment]
It'd appear its consumed in https://github.com/theodi/odlifier/blob/60d8d808f3b283a7c58d8c727ef0705ae30962f9/lib/odlifier.rb which is used in 3 other ODI projects https://github.com/theodi/odlifier/network/dependents

Hopefully it'll  be easy for them to become `legacy_id` aware in odlifier?

**Comment by Floppy** [comment]
I'm not there any more, but yes, one of us could easily update `odlifier` to use something like `legacy_id`.

**Comment by mlinksva** [comment]
@Floppy I made a crude attempt at https://github.com/theodi/odlifier/pull/56 ... untested, I'm not good at Ruby and don't grok the VCR stuff in tests. 😬  🗑 

Anyway, I'll merge https://github.com/okfn/licenses/pull/69 (changes `id` of a few licenses to SPDX assignment, adds `legacy_id` to those) when I hear from you that it's handled by ODI's tools, or in some months if nobody cares. :smile:

**Comment by mlinksva** [comment]
Has been some months, assume nobody cares so merged #69  🎉
