### ISSUE TITLE
Add test to check licenses.csv against datapackage.json

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/licenses#58]
Based on http://okfnlabs.org/blog/2016/05/17/automated-data-validation.html

Especially important if constraints are added to schema

**Comment by rufuspollock** [comment]
@Stephen-Gates +1 and you can use goodtables.io (or this will soon be integrated into the new release of datahub.io)

**Comment by Stephen-Gates** [comment]
Used goodtables.io for #57
 
[![goodtables.io](https://goodtables.io/badge/github/Stephen-Gates/licenses.svg)](https://goodtables.io/github/Stephen-Gates/licenses)

**Comment by Stephen-Gates** [comment]
@rufuspollock can you set up goodtables.io to test [licenses.csv[(https://raw.githubusercontent.com/okfn/licenses/master/licenses.csv) against [datapackage.json](https://raw.githubusercontent.com/okfn/licenses/master/datapackage.json) and add the badge link to the readme? I don't have rights to use this repo in GoodTables.

**Comment by rufuspollock** [comment]
@Stephen-Gates what would it take for you to get able to do that - i'd prefer to sort that than directly fix so that you are empowered on these things in the future.

/cc @mlinksva

**Comment by Stephen-Gates** [comment]
@rufuspollock I believe I'd need some level of rights to the repository to register it with GoodTables.io for continuous integration.

**Comment by mlinksva** [comment]
@Stephen-Gates sent you an invite, accept and you should be able to add webhooks to this repo.

**Comment by Stephen-Gates** [comment]
Thanks @mlinksva, accepted and will now progress automating validation of csv using good tables.io and add a badge to the readme
