### ISSUE TITLE
add french open licence

### ISSUE THREAD

**Issue by akakeronos** [okfn/licenses#59]
Hi,
Would it be possible to add the French official open licence into the opendeifinition repo so it can be used inside CKAN to attribute a correct openness status to the datasets published with this licence ?
https://www.etalab.gouv.fr/licence-ouverte-open-licence

Thanks

**Comment by rufuspollock** [comment]
@akakeronos sure - do a pull request.

BTW: it would also be good if this license got submitted through the Open Definition approval process if it hasn't already http://opendefinition.org/licenses/process/

**Comment by akakeronos** [comment]
Ok will do thanks

**Comment by mlinksva** [comment]
#60 fixed
