### ISSUE TITLE
Repository labels

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/licenses#65]
I've added a couple of labels to the repository issues. I'm happy to change these.

Is there a standard list of labels OKI prefers to use to manage issues? The ODI have some [recommendations](https://github.com/theodi/toolbox/wiki/Labels-In-Use-Across-the-ODI-Toolbox) that I've used successfully.

**Comment by rufuspollock** [comment]
@Stephen-Gates i'm sure what you've got is fine. In terms of recommendations at Open Knowledge the place to comment and look is probably https://github.com/okfn/coding-standards/issues/17
