### ISSUE TITLE
some license identifiers conflict with SPDX

### ISSUE THREAD

**Issue by mlinksva** [okfn/licenses#67]
ex [ODC-PDDL-1.0](https://github.com/okfn/licenses/blob/39d1256d48e3cb2b6d26aa8f306f9d78fd18ad68/licenses/ODC-PDDL-1.0.json) vs [PDDL-1.0](https://spdx.org/licenses/PDDL-1.0.html)

Some of these either weren't caught in #25 and #35 or they didn't have SPDX IDs at the time.

**Comment by rufuspollock** [comment]
@mlinksva good catch. What would be the upgrade PR?
