### ISSUE TITLE
Add French open license inside ckan group

### ISSUE THREAD

**Issue by akakeronos** [okfn/licenses#68]
I would like to add the French License https://github.com/okfn/licenses/blob/master/licenses/LO-2.0.json inside the group/ckan.json file
### Expected Behaviour
The definition of the license LO-2.0 is added to the json file

### Desired Behaviour (for enhancement suggestions only)
This addition is managed automaticaly
### Current Behaviour (for problems)
The license has been added to the list of the opense license but I do not know what is expected to make it available inside the file consumed by CKAN
### Your Environment
I use CKAN 2.6

**Comment by mlinksva** [comment]
According to the CKAN documentation you can [configure your instance](https://github.com/ckan/ckan/blob/71e839ab461ca072302381781f040a12708ce52b/doc/maintaining/configuration.rst#licenses_group_url) to use http://licenses.opendefinition.org/licenses/groups/all.json which includes LO-2.0.

I don't know what the criteria are for adding to the `ckan` group, but I _imagine_ they would include Open Definition Advisory Committee approval, which LO-2.0 hasn't been run through.

Anyway, it seems that adding to the `ckan` group here won't add to CKAN's default/unconfigured list of licenses:

> by default, the system will use an internal cached version of the CKAN list of licenses 

That internal cached version seems to be hardcoded at https://github.com/ckan/ckan/blob/d73326ad4beb3743cb4a347b15c04dace8c8654b/ckan/model/license.py#L89-L114

I don't think there's anything to do in this repo for now. Hopefully the configuration option works for you. If you or anyone is interested in seeing LO-2.0 vetted through http://opendefinition.org/licenses/process/ please do submit it.

**Comment by akakeronos** [comment]
ok thanks
