### ISSUE TITLE
DNS misconfigured for licenses.opendefinition.org?

### ISSUE THREAD

**Issue by mlinksva** [okfn/licenses#74]
https://github.com/okfn/licenses/settings has

![screen shot 2018-04-02 at 7 51 32 pm](https://user-images.githubusercontent.com/40415/38226680-bf5726fc-36af-11e8-985f-b38a8be20ca6.png)

> $ dig licenses.opendefinition.org
> 
> ...
> 
> licenses.opendefinition.org. 85841 IN	CNAME	**licenses.github.com**.

I gather from https://help.github.com/articles/troubleshooting-custom-domains/#dns-record-doesnt-point-to-githubs-server the CNAME should instead be **okfn.github.io**.

I've lost track of who might be a OK sysadmin so I will just ping @rufuspollock and 🙏 😄

**Comment by rufuspollock** [comment]
@mlinksva i'm acking and cc'ing @vitorbaptista @serahrono 

Note the site does seem to be working ok for licenses.opendefinition.org atm afaict ...

**Comment by mlinksva** [comment]
Hmm, I guess it's not a problem after all. I thought it might be a barrier to enabling https, but it works.
