### ISSUE TITLE
licenses.csv is not generated from json datafiles

### ISSUE THREAD

**Issue by mlinksva** [okfn/licenses#79]
It looks like licenses.csv was introduced in https://github.com/okfn/licenses/pull/46 but is manually maintained, allowing it to get out of sync as noticed in #78 

It seems that `bin/deploy.py` ought generate the CSV file.

**Comment by mlinksva** [comment]
This would be a relatively easy contribution for anyone who knows or probably is learning Python. 😄

**Comment by arielferdman** [comment]
I can try to do it if this repository is still active.

@mlinksva - waiting for your feedback.

**Comment by mlinksva** [comment]
@arielferdman it's obviously not very active, but I'm happy to merge a fix for this issue!

**Comment by arielferdman** [comment]
@mlinksva great :) because i use it at my workplace - and it helps us - would love to give something back!

on it.

**Comment by arielferdman** [comment]
@mlinksva - done :)
