### ISSUE TITLE
Add Eclipse License version 2.0

### ISSUE THREAD

**Issue by sandervdwaal** [okfn/licenses#88]
I noted that EPL v.2.0 was not yet added to this repository.

I created the changes needed and submitted them as pull requests (apologies for having them as separate PRs - I did this via the UI). 

Can anyone check and merge them in if they look ok?

**Comment by mlinksva** [comment]
Thanks!

You can add multiple commits to a single PR via the web UI. Just keep editing on a single branch used/to be used for the PR.

Could you consolidate into a single PR? It's kind of hard to tell how it all fits together spread across 7.

**Comment by sandervdwaal** [comment]
I'll do that Mike, thanks.

**Comment by sandervdwaal** [comment]
This is now all in https://github.com/okfn/licenses/pull/81 if you've got time to review @mlinksva ? Thanks!

**Comment by mlinksva** [comment]
Thanks, merged!

FWIW it is only really necessary to add/edit licenses' `.json` files in `licenses`. Everything else should be generated by running `bin/deploy.py run`. (Well, the `.csv` file needs to be manually updated.) I ran the script and caught one [incorrect file name](https://github.com/okfn/licenses/commit/b300dfb9752baf9cb32a1fdec5e67278cb2bcd59#diff-8e611f72fd7bd2ac78a7dbe64dc6de35) and got a couple other generated files updated.
