### ISSUE TITLE
:pray:  Missing licences > CC BY-ND 4.0, CC BY-NC-SA 4.0,CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by adriens** [okfn/licenses#95]
# :grey_question: Context

I'm currently working on an open data project in New-Caledonia and I need to get some proper licences data.
I found your site very helpful but I'm missing the following ones : 

- [x] [`CC BY-ND 4.0`](https://creativecommons.org/licenses/by-nd/4.0)
- [x] [`CC BY-NC-SA 4.0`](https://creativecommons.org/licenses/by-nc-sa/4.0)
- [x] [`CC BY-NC-ND 4.0`](https://creativecommons.org/licenses/by-nc-nd/4.0)

# :ticket: Related issues

- https://github.com/adriens/odata-data-gouv-nc/issues/7

**Comment by rufuspollock** [comment]
@adriens good point - would you be up for opening a pull request to fix that?

**Comment by adriens** [comment]
Yup, I could, is the only thing to do is to manually feed the `licenses.csv` ?

**Comment by rufuspollock** [comment]
@adriens you actually just create them as json files in https://github.com/okfn/licenses/tree/master/licenses see e.g. https://github.com/okfn/licenses/blob/master/licenses/CC-BY-4.0.json

Note the NC licenses are all **not open** (that's why they weren't in here before) -- see e.g. https://blog.okfn.org/2010/06/24/why-share-alike-licenses-are-open-but-non-commercial-ones-arent/ and https://blog.okfn.org/2012/10/04/making-a-real-commons-creative-commons-should-drop-the-non-commercial-and-no-derivatives-licenses/

So if you add them you need to make sure you have `  "od_conformance": "rejected"` -- see e.g. https://github.com/okfn/licenses/blob/master/licenses/ukclickusepsi.json

**Comment by adriens** [comment]
I have created three distincts PRs for an easier review process :crossed_fingers: 

- https://github.com/okfn/licenses/pull/98
- https://github.com/okfn/licenses/pull/97
- https://github.com/okfn/licenses/pull/96

**Comment by rufuspollock** [comment]
@adriens thanks!

@mlinksva @Stephen-Gates @ldodds @jwyg  would love your thoughts and comments here before merging. I think it makes sense to have these in if properly flagged as "not open".

**Comment by hlainchb** [comment]
I think it makes sense.

**Comment by Stephen-Gates** [comment]
Agreed

**Comment by adriens** [comment]
:smile_cat: :crossed_fingers:

**Comment by adriens** [comment]
:open_hands:

**Comment by rufuspollock** [comment]
FIXED. Have merged the PRs for this. 👍

**Comment by adriens** [comment]
so.... we are all good ❔ 🤩

**Comment by adriens** [comment]
Looks like I cannot find them on the csv :pray: :sweat_smile:

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/227406906-e60871b0-e2cf-43cb-ad5e-bead82af4069.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/227406998-520f9bdc-7059-4828-9442-e0e23dd57fdf.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/227407145-fa989878-811a-4119-8616-44d3656c4c67.png)

**Comment by mlinksva** [comment]
@adriens the CSV file is generated by a script. Fixed various small issues (and one largish--ND is not OD conformant) with the added licenses, ported the script to python 3, ran the script in #100

**Comment by adriens** [comment]
Yup, now everything works out of the box, check this

```sql
select * from 
read_csv_auto('https://raw.githubusercontent.com/okfn/licenses/master/licenses.csv')
where
    id like 'CC-BY-ND%' or
    id like 'CC-BY-NC%';
```

![image](https://user-images.githubusercontent.com/5235127/227463125-e8f5e5ad-0258-4ca0-bce5-4870c3686625.png)
